[package]
name = "git-dit-github-import"
version = "0.1.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

[dependencies]
hubcaps    = "0.4"
hyper      = "0.11"
tokio-core = "0.1"
clap       = "2"
futures    = "0.1"
indicatif  = "0.8"
libgitdit  = "0.4"
git2       = "0.6"
chrono     = "0.4"
